// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBackerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBackerSystem {
  function app__backerDeposit() external payable;

  function app__backerReqClaim() external;

  function app__backerClaim(uint256 reqId) external;
}
