// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICharacterSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICharacterSystem {
  function app__delegateSessionWallet(uint256 characterId, address sessionWallet) external;

  function app__revokeSessionWallet(uint256 characterId) external;

  function app__linkMainAccount(uint256 characterId, address newOwner) external;
}
