// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICitySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICitySystem {
  function app__upgradeCity(uint256 characterId, uint256 cityId) external;

  function app__cityHealing(uint256 characterId, uint256 cityId) external;

  function app__citySavePoint(uint256 characterId, uint256 cityId) external;

  function app__cityTeleport(uint256 characterId, uint256 fromCityId, uint256 toCityId) external;
}
