// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TargetItemData } from "@utils/ConsumeUtils.sol";

/**
 * @title IConsumeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IConsumeSystem {
  function app__eatBerries(uint256 characterId, uint256 itemId, uint32 amount) external;

  function app__consumeItem(
    uint256 characterId,
    uint256 itemId,
    uint32 amount,
    TargetItemData calldata targetData
  ) external;
}
