// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemsActionData } from "@common/Types.sol";

/**
 * @title IDropSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDropSystem {
  function app__drop(uint256 characterId, ItemsActionData calldata dropData) external;
}
