// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EquipData } from "@utils/CharacterEquipmentUtils.sol";
import { SlotType } from "@codegen/common.sol";

/**
 * @title IEquipmentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEquipmentSystem {
  function app__gearUpEquipments(uint256 characterId, EquipData[] calldata equipDatas) external;

  function app__updateGrindSlot(uint256 characterId, SlotType slotType) external;

  function app__upgradeEquipment(uint256 characterId, uint256 targetEquipmentId, uint256 materialEquipmentId) external;
}
