// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IExpeditionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IExpeditionSystem {
  function app__attackTowerMonster(uint256 characterId, uint256 towerId, uint16 floor) external;

  function app__buyExpeditionAttack(uint256 characterId, uint8 attackCount) external;

  function app__exploreExpedition(uint256 characterId, uint256 towerId, uint256[] calldata pochiIds) external;
}
