// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFarmingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFarmingSystem {
  function app__startFarming(uint256 characterId, uint256 resourceItemId, uint256 toolId, bool claimResource) external;

  function app__finishFarming(uint256 characterId, bool continueFarming, bool claimResource) external;
}
