// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGuildSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGuildSystem {
  function app__createGuild(uint256 characterId, string memory name) external;

  function app__transferGuildOwnership(uint256 characterId, uint256 newOwnerId) external;

  function app__leaveGuild(uint256 characterId) external;

  function app__kickMember(uint256 characterId, uint256[] calldata memberIds) external;

  function app__requestToJoinGuild(uint256 characterId, uint256 guildId) external;

  function app__cancelJoinGuildRequest(uint256 characterId) external;

  function app__approveJoinGuildRequest(uint256 characterId, uint256[] calldata memberIds) external;

  function app__rejectJoinGuildRequest(uint256 characterId, uint256[] calldata memberIds) external;
}
