// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RoleType } from "@codegen/common.sol";
import { VaultRestrictionParam } from "@common/Types.sol";

/**
 * @title IKingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IKingSystem {
  function app__registerKing(uint256 characterId, string memory promiseSummary) external;

  function app__assignKing(uint8 kingdomId) external;

  function app__voteKing(uint256 characterId, uint256 candidateId) external;

  function app__setAlliance(uint256 characterId, uint8 otherKingdomId, bool value) external;

  function app__setMarketFee(uint256 characterId, uint8[] calldata kingdomIds, uint8[] calldata fees) external;

  function app__setCrystalFee(uint256 characterId, uint8 fee) external;

  function app__setPvPFamePenalty(uint256 characterId, uint8 penalty) external;

  function app__setCaptureTileFamePenalty(uint256 characterId, uint8 penalty) external;

  function app__setNewCity(uint256 characterId, int32 x, int32 y, string memory name) external;

  function app__moveCity(uint256 characterId, int32 x, int32 y, uint256 cityId) external;

  function app__setRole(uint256 characterId, uint256 citizenId, RoleType role) external;

  function app__setWithdrawWeightLimit(uint256 characterId, uint32 weightLimit) external;

  function app__setWithdrawRestriction(uint256 characterId, VaultRestrictionParam[] calldata data) external;
}
