// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemType } from "@codegen/common.sol";
import { IncreaseStatData } from "@common/Types.sol";

/**
 * @title ILevelSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILevelSystem {
  function app__levelUp(uint256 characterId, uint16 amount) external;

  function app__levelUpPerk(uint256 characterId, ItemType itemType, uint8 amount) external;

  function app__increaseStats(uint256 characterId, IncreaseStatData[] calldata datas) external;
}
