// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { OrderParams, TakeOrderParams } from "@utils/MarketSystemUtils.sol";

/**
 * @title IMarketSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMarketSystem {
  function app__placeOrder(uint256 characterId, OrderParams memory orderParams) external;

  function app__cancelOrder(uint256 characterId, uint256 orderId) external;

  function app__takeOrder(uint256 characterId, TakeOrderParams[] calldata takeParams) external;

  function app__upgradeMarketWeight(uint256 characterId, uint256 cityId) external;
}
