// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title INestSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface INestSystem {
  function app__buildNest(uint256 characterId, uint256[] memory resourceIds, uint256[] memory petIds) external;

  function app__harvestNest(uint256 characterId) external;

  function app__removeNest(uint256 characterId) external;
}
