// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { NpcTradeData } from "@common/Types.sol";

/**
 * @title INpcShopSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface INpcShopSystem {
  function app__tradeWithNpc(
    uint256 characterId,
    uint256 cityId,
    NpcTradeData[] calldata buyData,
    NpcTradeData[] calldata sellData
  ) external;
}
