// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPortalSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPortalSystem {
  function app__appDeposit() external payable;

  function app__buyCrystal(uint256 characterId, uint256 amount) external payable;

  function app__transferCrystal(uint256 fromCharacterId, uint256 toCharacterId, uint256 amount) external;

  function app__requestSellCrystal(uint256 characterId, uint256 amount) external;

  function app__cancelSellCrystal(uint256 characterId, uint256 reqId) external;

  function app__executeSellCrystal(uint256 characterId, uint256 reqId) external;
}
