// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CharPositionData } from "@common/Types.sol";

/**
 * @title IPvESystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPvESystem {
  function app__pveAFK(uint256 characterId, uint256 monsterId, bool stop) external;

  function app__battlePvE(uint256 characterId, uint256 monsterId, bool claimItem) external;

  function app__attackNest(uint256 characterId) external;

  function app___attackNestAtPosition(uint256 characterId, CharPositionData memory characterPosition) external;
}
