// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SocialType } from "@codegen/common.sol";

/**
 * @title IQuestSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IQuestSystem {
  function app__receiveQuest(uint256 characterId, uint256 fromNpcId, uint256 questId) external;

  function app__finishQuest(uint256 characterId, uint256 toNpcId, uint256 questId) external;

  function app__finishSocialQuest(uint256 characterId, SocialType socialType) external;
}
