// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRescueSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRescueSystem {
  function app__rescue(
    uint256 characterId,
    uint256[] calldata cityIds,
    uint256[] calldata inventoryOtherItemIds
  ) external;
}
