// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EquipSkinData } from "@utils/CharacterEquipmentUtils.sol";

/**
 * @title ISkinSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISkinSystem {
  function app__equipSkins(uint256 characterId, EquipSkinData[] calldata equipData) external;
}
