// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemsActionData } from "@common/Types.sol";

/**
 * @title IStorageSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStorageSystem {
  function app__upgradeStorage(uint256 characterId, uint256 cityId) external;

  function app__updateStorage(
    uint256 characterId,
    uint256 cityId,
    ItemsActionData calldata transferIn,
    ItemsActionData calldata transferOut
  ) external;
}
