// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LootItems } from "@utils/TileInventoryUtils.sol";

/**
 * @title ITileSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITileSystem {
  function app__occupyTile(uint256 characterId) external;

  function app__lootItems(uint256 characterId, LootItems calldata data) external;
}
