// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { VaultActionParams } from "@common/Types.sol";

/**
 * @title IVaultSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVaultSystem {
  function app__withdrawItemFromCity(uint256 characterId, uint256 cityId, VaultActionParams calldata params) external;

  function app__contributeItemToCity(uint256 characterId, uint256 cityId, VaultActionParams calldata params) external;
}
